# config.yaml

models:
  sentiment_model: "distilbert-base-uncased-finetuned-sst-2-english"

bias_terms:
  # Negative Sentiment Terms
  - alarming
  - allegations
  - unfit
  - aggressive
  - alleged
  - apparently
  - arguably
  - claims
  - controversial
  - disputed
  - insists
  - questionable
  - reportedly
  - rumored
  - suggests
  - supposedly
  - unconfirmed
  - suspected
  - reckless
  - radical
  - extremist
  - biased
  - manipulative
  - deceptive
  - unbelievable
  - incredible
  - shocking
  - outrageous
  - bizarre
  - absurd
  - ridiculous
  - disgraceful
  - disgusting
  - horrible
  - terrible
  - unacceptable
  - unfair
  - scandalous
  - suspicious
  - illegal
  - illegitimate
  - immoral
  - corrupt
  - criminal
  - dangerous
  - threatening
  - harmful
  - menacing
  - disturbing
  - distressing
  - troubling
  - fearful
  - afraid
  - panic
  - terror
  - catastrophe
  - disaster
  - chaos
  - crisis
  - collapse
  - failure
  - ruin
  - devastation
  - suffering
  - misery
  - pain
  - dreadful
  - awful
  - nasty
  - vile
  - vicious
  - brutal
  - violent
  - greedy
  - selfish
  - arrogant
  - ignorant
  - stupid
  - unwise
  - illogical
  - unreasonable
  - delusional
  - paranoid
  - obsessed
  - fanatical
  - zealous
  - militant
  - dictator
  - regime

scoring:
  sentiment_weight: 0.4
  bias_weight: 0.3
  propaganda_weight: 0.3
  max_bias: 20
  max_propaganda: 20
